config/routes.rb
Ecomm::Engine.routes.draw do
  root to: 'carts#show'

  resource :cart, only: [:show, :update]
  resources :cart_items, only: [:create, :destroy]

  scope 'checkout' do
    Ecomm.checkout_steps.each do |action|
      get action, to: "checkout##{action}", as: "checkout_#{action}"

      next if action == Ecomm.checkout_steps.last

      post action, to: "checkout#submit_#{action}",
                   as: "checkout_submit_#{action}"
    end
  end
end

app/models/ecomm/address.rb
module Ecomm
  class Address < ApplicationRecord
    belongs_to :customer, class_name: Ecomm.customer_class.to_s, optional: true
    belongs_to :order, optional: true

    scope :billing, -> { where(address_type: 'billing') }
    scope :shipping, -> { where(address_type: 'shipping') }
  end
end

app/models/ecomm/application_record.rb
module Ecomm
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/ecomm/coupon.rb
module Ecomm
  class Coupon < ApplicationRecord
    has_one :order
  end
end

app/models/ecomm/credit_card.rb
module Ecomm
  class CreditCard < ApplicationRecord
    belongs_to :order
  end
end

app/models/ecomm/line_item.rb
module Ecomm
  class LineItem < ApplicationRecord
    belongs_to :product, class_name: Ecomm.product_class.to_s
    belongs_to :order
  end
end

app/models/ecomm/order.rb
module Ecomm
  class Order < ApplicationRecord
    belongs_to :customer, optional: true, class_name: Ecomm.customer_class.to_s
    belongs_to :coupon, optional: true
    belongs_to :shipment
    has_many :line_items, dependent: :destroy
    has_many :addresses, dependent: :destroy
    has_one :billing_address, -> { billing }, class_name: 'Ecomm::Address'
    has_one :shipping_address, -> { shipping }, class_name: 'Ecomm::Address'
    has_one :credit_card, dependent: :destroy

    monetize :subtotal_cents
  end
end

app/models/ecomm/shipment.rb
module Ecomm
  class Shipment < ApplicationRecord
    has_many :orders
    monetize :price_cents
  end
end

app/controllers/ecomm/application_controller.rb
module Ecomm
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
    helper_method :current_customer
    before_action { session[:cart] ||= Hash.new(0) }

    def current_customer
      public_send(Ecomm.current_customer_method)
    end

    private

    def authenticate_customer
      return if current_customer
      session[Ecomm.flash_login_return_to] = request.fullpath
      flash.alert = t(Ecomm.i18n_unuathenticated_key)
      redirect_to(Ecomm.signin_path)
    end
  end
end

app/controllers/ecomm/cart_items_controller.rb
module Ecomm
  class CartItemsController < Ecomm::ApplicationController
    def create
      product_id = params[:id]
      quantity = params[:quantity].present? ? params[:quantity].to_i : 1
      session[:cart][product_id] ||= 0
      session[:cart][product_id] += quantity
      flash.keep
      redirect_back(fallback_location: main_app.root_path)
    end

    def destroy
      session[:cart].except!(params[:id])
      redirect_to(cart_path)
    end
  end
end

app/controllers/ecomm/carts_controller.rb
module Ecomm
  class CartsController < Ecomm::ApplicationController
    def show
      @line_items = Ecomm::Common::BuildLineItemsFromCart.call(session[:cart])
      totals = Ecomm::Cart::CalculateCartTotals.call(session)
      @items_total, @order_subtotal, @discount = totals
      session[:items_total] = @items_total
      session[:order_subtotal] = @order_subtotal
    end

    def update
      params[:quantities].each do |product_id, quantity|
        session[:cart][product_id] = quantity.present? ? quantity.to_i : 1
      end

      handle_coupon if params[:coupon].present?

      redirect_to(params[:to_checkout] ? checkout_address_path : cart_path)
    end

    private

    def handle_coupon
      Ecomm::Cart::HandleCoupon.call(params[:coupon]) do
        on(:error) do |error_message|
          flash[:alert] = error_message
          flash.keep
        end

        on(:ok) do |coupon|
          session[:coupon_id] = coupon.id
          session[:discount] = coupon.discount
        end
      end
    end
  end
end

app/controllers/ecomm/checkout_controller.rb
module Ecomm
  class CheckoutController < Ecomm::ApplicationController
    include Rectify::ControllerHelpers

    steps = Ecomm.checkout_steps

    before_action(:authenticate_customer)
    before_action(-> { present CheckoutPresenter.new }, only: steps)

    steps.each do |step|
      define_method(step) do
        command = "Ecomm::Checkout::Show#{step.capitalize}Step".constantize
        command.call(session, flash, current_customer.id) do
          on(:ok) { |step_variables| expose(step_variables) }
          on(:denied) { |failure_path| redirect_to(failure_path) }
        end
      end

      next if step == steps.last

      define_method("submit_#{step}") do
        command = "Ecomm::Checkout::Submit#{step.capitalize}Step".constantize
        command.call(session, params, flash, current_customer.id) do
          on(:ok) { |ok_path| redirect_to(ok_path) }
          on(:error) { |error_path| redirect_to(error_path) }
        end
      end
    end
  end
end

app/helpers/ecomm/application_helper.rb
module Ecomm
  module ApplicationHelper
    def completed_order_url(order)
      main_app.send(Ecomm.completed_order_url_helper_method, order)
    end
  end
end

app/views/ecomm/carts/_cart_items.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600.ml-20= t('ecomm.carts.product')
    %th.col-title
    %th.col-price
      %span.in-grey-600= t('ecomm.carts.price')
    %th.col-quantity
      %span.in-grey-600= t('ecomm.carts.quantity')
    %th.col-total
      %span.in-grey-600= t('ecomm.carts.subtotal')
    - if render_inputs
      %th.col-close
  - @line_items.each do |line_item|
    %tr
      %td
        .general-img-wrap-table
          = image_tag(line_item.product.main_image,
            alt: line_item.product.title, class: 'cart-img-shadow pull-left')
      %td
        %p.general-title= line_item.product.title
        - unless render_inputs
          %p.text-justify.in-grey-600.font-weight-light= |
            truncate(line_item.product.description, length: 150) |
      %td
        %span.font-16.in-gold-500= number_to_currency(line_item.product.price)
      %td
        - if render_inputs
          .input-group
            %a.input-link.quantity-decrement{href: '#',
              'data-target': "quantities-#{line_item.product_id}"}
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{type: 'number', min: '1',
              name: "quantities[#{line_item.product_id}]",
              class: "quantities-#{line_item.product_id}",
              id: "quantities-#{line_item.product_id}",
              'data-bound-input': "xs-quantities-#{line_item.product_id}",
              'data-bound-subtotal': "subtotal-#{line_item.product_id}",
              'data-price': line_item.product.price,
              value: line_item.quantity}
            %a.input-link.quantity-increment{href: '#',
              'data-target': "quantities-#{line_item.product_id}"}
              %i.fa.fa-plus.line-height-40
        - else
          %span.ml-30= line_item.quantity
      %td
        %span.font-16.in-gold-500{class: "subtotal-#{line_item.product_id}"}= |
          number_to_currency(line_item.product.price * line_item.quantity) |
      - if render_inputs
        %td
          = link_to(cart_item_path(line_item.product_id),
            data: { confirm: t('ecomm.carts.show.are_you_sure') },
            class: 'close general-cart-close', method: :delete) do
            %span{'aria-hidden': 'true'} &times;

app/views/ecomm/carts/_xs_cart_items.html.haml
- @line_items.each do |line_item|
  - if render_inputs
    = link_to(cart_item_path(line_item.product_id),
      data: { confirm: t('ecomm.carts.show.are_you_sure') },
      class: 'close general-cart-close', method: :delete) do
      %span{'aria-hidden': 'true'} &times;
  .general-img-wrap-table
    = image_tag(line_item.product.main_image, alt: line_item.product.title,
      class: 'cart-image-shadow')
  %p.general-title= line_item.product.title
  - unless render_inputs
    %p.text-justify.in-grey-600.font-weight-light= |
      truncate(line_item.product.description, length: 150) |
  %table.table
    %tr
      %td
        %span.in-grey-600= t('ecomm.carts.price')
      %td
        %span.font-16.in-gold-500= number_to_currency(line_item.product.price)
    %tr
      %td.vertical-middle
        %span.in-grey-600= t('ecomm.carts.quantity')
      %td
        - if render_inputs
          .input-group
            %a.input-link.quantity-decrement{href: '#',
              'data-target': "xs-quantities-#{line_item.product_id}"}
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{type: 'number', min: '1',
              name: "quantities[#{line_item.product_id}]",
              class: "quantities-#{line_item.product_id}",
              id: "xs-quantities-#{line_item.product_id}",
              'data-bound-input': "quantities-#{line_item.product_id}",
              'data-bound-subtotal': "subtotal-#{line_item.product_id}",
              'data-price': line_item.product.price,
              value: line_item.quantity}
            %a.input-link.quantity-increment{href: '#',
              'data-target': "xs-quantities-#{line_item.product_id}"}
              %i.fa.fa-plus.line-height-40
        - else
          %span= line_item.quantity
    %tr
      %td
        %span.in-grey-600= t('ecomm.carts.subtotal')
      %td
        %span.font-16.in-gold-500{class: "subtotal-#{line_item.product_id}"}= |
          number_to_currency(line_item.product.price * line_item.quantity) |
  .general-cart-item.divider-lg-bottom.mb-30

app/views/ecomm/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('.caption')
  - if @line_items.empty?
    .container.text-center.mt-50
      %h2= t('.cart_empty_html', href: link_to(t('.catalog_caption'),
        Ecomm.catalog_path))
  - else
    = form_tag(cart_path, method: :put) do
      .visible-xs
        = render('xs_cart_items', render_inputs: true)
      .hidden-xs
        = render('cart_items', render_inputs: true)
      .general-order-wrap
        .row
          .col-sm-4
            .input-group.general-input-group
              %label.font-weight-light= t('.enter_coupon')
              %input.form-control.mb-30{type: 'text', name: 'coupon', |
                placeholder: t('.enter_coupon')} |
              %div
                = submit_tag(t('.update_cart'),
                  class: 'btn btn-primary mb-15 res-block')
          .col-sm-8
            .res-mr-200.text-center.general-text-right
              %p.in-gold-500.font-18= t('.order_summary')
              %table.general-summary-table.general-summary-table-right.general-text-right
                %tr
                  %td
                    %p.font-16= t('.subtotal')
                  %td
                    %p#items-total.font-16{'data-discount': session[:discount]}= |
                      number_to_currency(@items_total) |
                %tr
                  %td
                    %p.font-16= t('.coupon')
                  %td
                    %p#discount.font-16= number_to_currency(@discount)
                %tr
                  %td
                    %strong.font-18= t('.order_total')
                  %td
                    %strong#order-subtotal.font-18= |
                      number_to_currency(@order_subtotal) |
        .text-center
          = submit_tag(t('.checkout'), class: 'btn btn-default mb-20',
            name: :to_checkout)

app/views/ecomm/checkout/_address_fields.html.haml
= f.simple_fields_for(type, address) do |fields|
  = fields.input(:id, as: :hidden)
  = fields.input(:address_type, as: :hidden)
  - %i(first_name last_name street_address city zip).each do |property|
    = fields.input(property, label: t("ecomm.checkout.address.#{property}"),
      placeholder: t("ecomm.checkout.address.#{property}"))
  = fields.input(:country, label: t('ecomm.checkout.address.country'),
    collection: presenter.populate_countries_for(type),
    input_html: { class: 'country-select', name: "#{entity}[#{type}][country]",
                  'data-target': "#{type}-phone" },
    prompt: t('ecomm.checkout.address.select_country'))
  = fields.input(:phone, label: t('ecomm.checkout.address.phone'),
    input_html: { id: "#{type}-phone" },
    placeholder: t('ecomm.checkout.address.phone_example'))

app/views/ecomm/checkout/_address_summary.html.haml
%p.general-address
  = "#{address.first_name} #{address.last_name}"
  - if render_edit_link
    %span.general-edit
      = link_to(t('ecomm.checkout.edit'), checkout_address_path)
  %br
  = address.street_address
  %br
  = "#{address.city} #{address.zip}"
  %br
  = address.country
  %br
  = "#{t('ecomm.checkout.address.phone')} #{address.phone}"

app/views/ecomm/checkout/_deliveries_radio.html.haml
%table.table.table-hover
  %thead
    %tr
      %th.col-method
        %span.in-grey-600.ml-40= t('ecomm.checkout.delivery.method')
      %th
        %span.in-grey-600= t('ecomm.checkout.delivery.days')
      %th
        %span.in-grey-600= t('ecomm.checkout.delivery.price')
  %tbody
    - @shipments.each do |shipment|
      %tr
        %td
          .form-group.radio.mt-0.mb-0
            %label.font-16.font-weight-light.pl-0
              = radio_button_tag(:shipment_id, shipment.id,
                shipment.id == @order.shipment_id,
                class: 'radio-input', hidden: 'true',
                id: "shipment-#{shipment.id}", 'data-price': shipment.price,
                'data-days-min': shipment.days_min,
                'data-days-max': shipment.days_max,
                'data-shipping-method': shipment.shipping_method)
              %span.radio-icon
              %span.radio-text= shipment.shipping_method
        %td
          %span #{shipment.days_min} to #{shipment.days_max} days
        %td
          %span.font-16.in-gold-500= number_to_currency(shipment.price)

app/views/ecomm/checkout/_delivery_totals.html.haml
%tr
  %td
    %p.font-16= t('ecomm.checkout.order_subtotal')
  %td
    %p.font-16= number_to_currency(@order.subtotal)
%tr
  %td
    %p.font-16= t('ecomm.checkout.shipping')
  %td
    %p#shipment-label.font-16= number_to_currency(@order.shipment.price)
%tr
  %td
    %strong.font-18= t('ecomm.carts.show.order_total')
  %td
    %strong#order-total-label.font-18{'data-subtotal': @order.subtotal.amount}= |
      number_to_currency(@order.subtotal + @order.shipment.price) |

app/views/ecomm/checkout/_order_details.html.haml
.row.mb-20
  .col-sm-3
    %h3.general-subtitle= t('ecomm.checkout.address.shipping_address')
    = render('ecomm/checkout/address_summary', address: @shipping,
      render_edit_link: render_links)
  .col-sm-3
    %h3.general-subtitle= t('ecomm.checkout.address.billing_address')
    = render('ecomm/checkout/address_summary', address: @billing,
      render_edit_link: render_links)
  .col-sm-3
    %h3.general-subtitle= t('ecomm.checkout.shipments')
    %p.general-address
      = @order.shipment.shipping_method
      -if render_links
        %span.general-edit
          = link_to(t('ecomm.checkout.edit'), ecomm.checkout_delivery_path)
      %br
      from #{@order.shipment.days_min} to #{@order.shipment.days_max} days
  .col-sm-3
    %h3.general-subtitle= t('ecomm.checkout.payment_info')
    %p.general-address
      = presenter.starred_number(@order.credit_card)
      - if render_links
        %span.general-edit
          = link_to(t('ecomm.checkout.edit'), ecomm.checkout_payment_path)
      %br
      = presenter.month_full_year(@order.credit_card)
.general-cart-item.divider-lg.visible-xs
.visible-xs
  = render('/ecomm/carts/xs_cart_items', render_inputs: false)
.hidden-xs.divider-lg.pt-20
  = render('/ecomm/carts/cart_items', render_inputs: false)
.text-center.general-text-right
  %p.in-gold-500.font-18= t('ecomm.carts.show.order_summary')
  %table.general-summary-table.general-summary-table-right.general-text-right
    = render('ecomm/checkout/delivery_totals')

app/views/ecomm/checkout/_progress.html.haml
%ul.steps.list-inline
  - presenter.steps.each_with_index do |step, index|
    - if presenter.previous?(step, action_name)
      %li.step.done
        %span.step-number
          %i.fa.fa-check.step-icon
        %span.step-text.hidden-xs= t("ecomm.checkout.steps.#{step}")
    - else
      %li.step{class: ('active' if presenter.current?(step, action_name))}
        %span.step-number= index + 1
        %span.step-text.hidden-xs= t("ecomm.checkout.steps.#{step}")
    - if index < presenter.steps.length - 1
      %li.step-divider

app/views/ecomm/checkout/_xs_deliveries_radio.html.haml
- @shipments.each do |shipment|
  %table.table
    %tr
      %td.col-half
        %span.in-grey-600= t('ecomm.checkout.delivery.method')
      %td.col-half
        .form-group.radio.mt-0.mb-0
          %label.font-16.font-weight-light.pl-0
            = radio_button_tag(:shipment_id, shipment.id,
              false,
              class: 'radio-input', hidden: true,
              id: "xs-shipment-#{shipment.id}", 'data-price': shipment.price,
                'data-days-min': shipment.days_min,
                'data-days-max': shipment.days_max,
                'data-shipping-method': shipment.shipping_method)
            %span.radio-icon
            %span.radio-text= shipment.shipping_method
    %tr
      %td
        %span.in-grey-600= t('ecomm.checkout.delivery.days')
      %td
        %span.font-16.font-weight-light |
          #{shipment.days_min} to #{shipment.days_max} days |
    %tr
      %td
        %span.in-grey-600= t('ecomm.checkout.delivery.price')
      %td
        %span.font-16.in-gold-500= number_to_currency(shipment.price)
  .general-cart-item.divider-lg-bottom.mb-30

app/views/ecomm/checkout/address.html.haml
%main.container
  %h1.general-title-margin= t('ecomm.checkout.caption')
  = render('progress')
  = form_for(@order, url: checkout_submit_address_path, class: 'res-mb-100') do |f|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle= t('.billing_address')
          %p.general-info-text= t('.fields_required')
        .col-md-5.col-md-offset-1.shipping-hideable{class: |
          ('hidden' if @order.use_billing)} |
          %h3.general-subtitle= t('.shipping_address')
    .row
      .col-md-5.mb-40
        .visible-xs.visible-sm
          %h3.general-subtitle= t('.billing_address')
          %p.general-info-text= t('.fields_required')
        = render('address_fields', f: f, address: @order.billing,
          type: 'billing', entity: 'order')
      .col-md-5.col-md-offset-1.mb-60
        .shipping-hideable{class: ('hidden' if @order.use_billing)}
          .visible-xs.visible-sm
            %h3.general-subtitle= t('.shipping_address')
          = render('address_fields', f: f, address: @order.shipping,
            type: 'shipping', entity: 'order')
        .form-group.checkbox
          %label.font-weight-light.pl-0
            = f.check_box(:use_billing, class: 'input checkbox-input',
              hidden: 'true')
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text= t('.use_billing')
    .general-text-align.mb-60
      %p.in-gold-500.font-18= t('ecomm.carts.show.order_summary')
      %table.general-summary-table
        %tr
          %td
            %p.font-16= t('.item_total')
          %td
            %p.font-16= number_to_currency(@order.items_total)
        %tr
          %td
            %p.font-16= t('ecomm.carts.show.order_total')
          %td
            %p.font-16= number_to_currency(@order.subtotal)
      = f.submit(t('ecomm.checkout.save_continue'),
        class: 'btn btn-default center-block mb-20')

app/views/ecomm/checkout/complete.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('ecomm.checkout.caption')
  = render('progress')
  .text-center.mb-40
    %h3.general-subtitle= t('.thanks')
    %p.font-weight-light #{t('.email_sent')} #{current_customer.email}
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0 #{t('.order')} ##{@order.number}
        %p.general-address.mb-30= l(@order.created_at, format: :long_date)
      = render('address_summary', address: @order.addresses.first,
        render_edit_link: false)
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0 #{t('.order')} ##{@order.number}
      %p.general-address.mb-30= l(@order.created_at, format: :long_date)
  .visible-xs
    .general-cart-item.divider-lg
      = render('/ecomm/carts/xs_cart_items', render_inputs: false)
  .hidden-xs.divider-lg.pt-20
    = render('/ecomm/carts/cart_items', render_inputs: false)
  .text-center.general-text-right
    %p.in-gold-500.font-18= t('ecomm.carts.show.order_summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render('delivery_totals')
  .text-center
    = link_to(t('.back_to_store'), Ecomm.catalog_path,
      class: 'btn btn-default mb-20')

app/views/ecomm/checkout/confirm.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('ecomm.checkout.caption')
  = render('progress')
  = render('order_details', render_links: true)
  = form_tag(checkout_submit_confirm_path) do
    .text-center
      = submit_tag(t('.place_order'), class: 'btn btn-default')

app/views/ecomm/checkout/delivery.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('ecomm.checkout.caption')
  = render('progress')
  = form_for(@order, url: checkout_submit_delivery_path, class: 'res-mb-100') do |f|
    %h3.general-subtitle= t('ecomm.checkout.delivery.shipping_method')
    .visible-xs
      = render('xs_deliveries_radio')
    .hidden-xs.mb-res-50
      = render('deliveries_radio')
    .general-text-align
      %p.in-gold-500.font-18= t('ecomm.carts.show.order_summary')
      %table.general-summary-table
        = render('delivery_totals')
    = fields_for(:shipment, @order.shipment) do |fields|
      = fields.hidden_field(:price, value: @order.shipment.price)
      = fields.hidden_field(:days_min, value: @order.shipment.days_min)
      = fields.hidden_field(:days_max, value: @order.shipment.days_max)
      = fields.hidden_field(:shipping_method,
                            value: @order.shipment.shipping_method)
    = f.submit(t('ecomm.checkout.save_continue'),
      class: 'btn btn-default center-block mb-20')

app/views/ecomm/checkout/payment.html.haml
%main.container.mb-res-50
  %h1.general-title-margin= t('ecomm.checkout.caption')
  = render('progress')
  %h3.general-subtitle= t('.credit_card')
  = form_for(@order, url: checkout_submit_payment_path,
    class: 'max-600 mb-80') do |f|
    .row
      .col-sm-6
        = f.simple_fields_for(:card, @order.card) do |fields|
          = fields.input(:number, label: t('.card_number'),
            input_html: { data: { mask: '9999-9999-9999-9999', placeholder: 'X' } },
            placeholder: t('.card_number'))
          .row
            .col-sm-6
              = fields.input(:cardholder, label: t('.cardholder'),
                placeholder: t('.cardholder'))
            .col-sm-3
              = fields.input(:month_year, label: t('.month_year'),
                placeholder: t('.month_year'))
            .col-sm-3
              = fields.input(:cvv, label: t('.cvv'), as: :password,
                wrapper_html: { class: 'relative' }, hint: '',
                hint_html: { title: t('.cvv_hint'),
                             data: { toggle: 'tooltip', placement: 'top' } },
                placeholder: t('.cvv'))
      .col-xs-12
        .general-text-align
          %p.in-gold-500.font-18= t('ecomm.carts.show.order_summary')
          %table.general-summary-table
            = render('delivery_totals')
        = f.submit(t('ecomm.checkout.save_continue'),
          class: 'btn btn-default center-block mb-20')